services:
  # Backend
  backend:
    build: ./backend
    container_name: nest-backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - db
    env_file:
      - ../.env
    volumes:
      - ./backend:/usr/src/app

  # Frontend
  frontend:
    build: ./web
    container_name: next-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./web:/usr/src/app

  # Redis
  # redis:
  #   image: redis:7
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"

  # PostgreSQL
#   db:
#     image: postgres:16
#     container_name: postgres-db
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: competitiondb
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:









